// Automatically generated by scripts/generate-resources.js
// Do not edit this file directly.

export interface GeneratedTopicResource {
  title: string;
  file: string;
  size: string;
  path: string;
}

export const TOPIC_RESOURCES: Record<string, GeneratedTopicResource[]> = {
  "abacus": [
    {
      "title": "Abacus Level 1 Workbook",
      "file": "Level1.pdf",
      "size": "5.4 MB",
      "path": "assets/Resources/Abacus/Level1.pdf"
    },
    {
      "title": "Abacus Level 2 Workbook",
      "file": "Level2.pdf",
      "size": "2 MB",
      "path": "assets/Resources/Abacus/Level2.pdf"
    },
    {
      "title": "Abacus Level 3 Workbook",
      "file": "Level3.pdf",
      "size": "2.7 MB",
      "path": "assets/Resources/Abacus/Level3.pdf"
    },
    {
      "title": "Abacus Level 5 Workbook",
      "file": "Level5.pdf",
      "size": "1.8 MB",
      "path": "assets/Resources/Abacus/Level5.pdf"
    },
    {
      "title": "Abacus Level 6 Workbook",
      "file": "Level6.pdf",
      "size": "2.4 MB",
      "path": "assets/Resources/Abacus/Level6.pdf"
    },
    {
      "title": "Abacus Level 7 Workbook",
      "file": "Level7.pdf",
      "size": "2.3 MB",
      "path": "assets/Resources/Abacus/Level7.pdf"
    },
    {
      "title": "Abacus Level 8 Workbook",
      "file": "Level8.pdf",
      "size": "2.6 MB",
      "path": "assets/Resources/Abacus/Level8.pdf"
    }
  ],
  "python": [
    {
      "title": "Learning Python",
      "file": "Learning Python",
      "size": "Web App",
      "path": "https://zy-innovators.github.io/learn-python/register"
    },
    {
      "title": "Python Book",
      "file": "Python Book.pdf",
      "size": "711.2 KB",
      "path": "assets/Resources/Python/Python Book.pdf"
    },
    {
      "title": "Python Workbook Answer Key (For Students)",
      "file": "Python Workbook Answer Key (For Students).pdf",
      "size": "649.3 KB",
      "path": "assets/Resources/Python/Python Workbook Answer Key (For Students).pdf"
    },
    {
      "title": "Python Workbook for Students",
      "file": "Python Workbook for Students.pdf",
      "size": "291.6 KB",
      "path": "assets/Resources/Python/Python Workbook for Students.pdf"
    },
    {
      "title": "Python Workbook for Teachers",
      "file": "Python Workbook for Teachers.pdf",
      "size": "905.3 KB",
      "path": "assets/Resources/Python/Python Workbook for Teachers.pdf"
    }
  ],
  "economics": [
    {
      "title": "Economics",
      "file": "Economics",
      "size": "Web App",
      "path": "https://zy-innovators.github.io/learn-economics/register"
    }
  ],
  "fp-pyjs": [
    {
      "title": "Functional Programming",
      "file": "Functional Programming",
      "size": "Web App",
      "path": "https://zy-innovators.github.io/learn-fp-pyjs/register"
    }
  ],
  "gofer": [
    {
      "title": "Gofer Functional Programming",
      "file": "Gofer Functional Programming",
      "size": "Web App",
      "path": "https://zy-innovators.github.io/learn-gofer/register"
    }
  ],
  "maths": [
    {
      "title": "Interactive Speed Maths Web App",
      "file": "Interactive Speed Maths Web App",
      "size": "Web App",
      "path": "https://zyarr-innovation.github.io/maths-app2/"
    },
    {
      "title": "testpdf",
      "file": "testpdf.pdf",
      "size": "0 Bytes",
      "path": "assets/Resources/maths/testpdf.pdf"
    }
  ],
  "probsolv": [
    {
      "title": "Problem Solving Guide",
      "file": "Problem Solving Guide",
      "size": "Web App",
      "path": "https://zy-innovators.github.io/learn-probsolv/register"
    }
  ],
  "proj-mgmt": [
    {
      "title": "Project Management",
      "file": "Project Management",
      "size": "Web App",
      "path": "https://zy-innovators.github.io/learn-proj-mgmt/register"
    }
  ],
  "science": [
    {
      "title": "My Beautiful Body - Gift of God",
      "file": "My Beautiful Body - Gift of God.pdf",
      "size": "300.6 KB",
      "path": "assets/Resources/science/My Beautiful Body - Gift of God.pdf"
    },
    {
      "title": "میرا خوبصورت جسم - خدا کا تحفہ (Urdu)",
      "file": "میرا خوبصورت جسم - خدا کا تحفہ.pdf",
      "size": "725.2 KB",
      "path": "assets/Resources/science/میرا خوبصورت جسم - خدا کا تحفہ.pdf"
    }
  ]
};
